apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cloudcost-ai-backend
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: cloudcost-ai-backend

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s