apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcost-ai-backend

spec:
  revisionHistoryLimit: 2
  strategy:
  type: RollingUpdate

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: cloudcost-ai-backend
  template:
    metadata:
      labels:
        app: cloudcost-ai-backend
    spec:
      containers:
      - name: cloudcost-ai-backend
        image: youssefcloudcostaidev.azurecr.io/cloudcost-ai-backend:bootstrap
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3

        resources:
        requests:
          cpu: "100m"
          memory: "256Mi"

        limits:
          cpu: "500m"
          memory: "512Mi"

        envFrom:
          - configMapRef:
              name: cloudcost-ai-backend-config
          - secretRef:
              name: cloudcost-ai-backend-secret