apiVersion: v1
kind: Secret

metadata:
  name: cloudcost-ai-backend-secret

type: Opaque

stringData:
  DATABASE_URL: "<DATABASE_URL>"
  JWT_SECRET: "<JWT_SECRET>"
  STRIPE_SECRET_KEY: "<STRIPE_SECRET_KEY>"
  STRIPE_WEBHOOK_SECRET: "<STRIPE_WEBHOOK_SECRET>"