apiVersion: v1
kind: Service

metadata:
  name: cloudcost-ai-backend-service

  labels:
    app: cloudcost-ai-backend

spec:
  type: ClusterIP

  selector:
    app: cloudcost-ai-backend

  ports:
    - name: http
      port: 80
      targetPort: 3000