flowchart LR

Bootstrap --> ResourceGroup

Bootstrap --> TerraformBackend

TerraformBackend --> StorageAccount

TerraformBackend --> BlobContainer

Dev --> Network

Dev --> AKS

Dev --> PostgreSQL

Dev --> KeyVault