apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: cloudcostaiyoussefdev.azurecr.io/cloudcost-ai-backend
    newTag: latest

  - name: cloudcostaiyoussefdev.azurecr.io/cloudcost-ai-frontend
    newTag: latest