apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: youssefcloudcostaidev.azurecr.io/cloudcost-ai-backend
    newTag: 37d2730

  - name: youssefcloudcostaidev.azurecr.io/cloudcost-ai-frontend
    newTag: 37d2730